// export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
// export const FETCH_USERS_SUCCESS = "FECT_USERS_SUCCESS";
export const ADD_USER = "ADD_USER";
export const SIGN_UP_USERS = "SIGN_UP_USERS";
